apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z mongodb 27017; do echo "Waiting for MongoDB"; sleep 2; done']
      containers:
        - name: backend
          image: user2106/blog-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PW)@mongodb:27017/blogdb?authSource=admin"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-username
            - name: MONGO_PW
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-password
            - name: PORT
              value: "5000"
          resources:
            limits:
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 10