apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: devblog
type: Opaque
data:
  # Username: bloguser (base64 encoded)
  MONGO_INITDB_ROOT_USERNAME: YmxvZ3VzZXI=
  # Password: blogpass123 (base64 encoded)
  MONGO_INITDB_ROOT_PASSWORD: YmxvZ3Bhc3MxMjM=